#!/usr/bin/env python3

import os, json
songs = {}
for f in os.listdir('songs'):
    with open('songs/' + f) as fh:
        songs[f] = fh.read()
with open('src/songs.json', 'w') as fh:
    fh.write(json.dumps(songs))
