#!/usr/bin/env python3

import os, json, re
songs = {}
byTitle = {}
for f in os.listdir('songs'):
    if not re.search(r'\.txt$', f, re.I):
        continue

    try:
        with open('songs/' + f) as fh:
            song = fh.read()
    except:
        with open('songs/' + f, encoding='latin-1') as fh:
            song = fh.read()

    songs[f] = song

    m = re.search(r'^T:\s*(.*)', song, re.MULTILINE)
    if m:
        title = m.group(1)
        byTitle[title] = song

    else:
        print('weird song:', f)
with open('src/songs.json', 'w') as fh:
    fh.write(json.dumps(songs))
with open('src/by-title.json', 'w') as fh:
    fh.write(json.dumps(byTitle))
